# Generated by Django 4.0.3 on 2022-03-31 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_remove_order_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount_paid',
        ),
    ]
