# Generated by Django 4.0.3 on 2022-03-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_alter_order_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='discount',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
