# Generated by Django 4.0.3 on 2022-03-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
