# Generated by Django 4.0.3 on 2022-03-31 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_order_item_price_alter_invoice_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item_price',
            new_name='selling_price',
        ),
    ]
