# Generated by Django 4.0.3 on 2022-04-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_rename_created_at_invoice_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='date_created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='time_created',
            new_name='time',
        ),
    ]
