# Generated by Django 4.0.3 on 2022-03-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='card_number',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
