# Generated by Django 4.0.3 on 2022-04-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customer_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.customergroup'),
        ),
    ]
