# Generated by Django 4.0.3 on 2022-03-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_brand_item_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='minimum_stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
